togglz:
  console:
    secured: false
    use-management-port: false
  cache:
    enabled: true
    time-to-live: 5
    time-unit: minutes
  feature-enums: com.eg.togglz.feature.definition.GainOnPrior_Definition,com.eg.togglz.feature.definition.GeoTab_Definition,com.eg.togglz.feature.definition.J875_Decomission_Definition,com.eg.togglz.feature.definition.ScheduledRelease_Definition
server:
  port: 80
spring:
  application:
    name: tooglz-demo
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/h2/togglz;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true